### ISSUE TITLE
mobile app issues

### ISSUE THREAD

**Issue by AliAlAbbassi** [Tooth-ly/monorepo#1]
There currently exists a generated directory in /apps, but it needs configuring, fixing errors, updating, and ofcourse hooking up the api.

**Comment by omar-bay** [comment]
Can it just be linked to another repo

**Comment by omar-bay** [comment]
we can commit the mobile app and unify the execution with nodemon

**Comment by AliAlAbbassi** [comment]
I've reopened this issue, since the problem haven't been resolved yet.

**Comment by TshiSelle** [comment]
tb is it resolved now ? WASGUUUU
